### ISSUE TITLE
Feature Request: mock network calls

### ISSUE THREAD

**Issue by IgorGanapolsky** [googlesamples/android-testing#45]
Hi,
can you please provide some samples with `MockWebServer` and `MockResponse` and stuff?  This will help developers understand how to test REST api's.

Thank you,
Igor

**Comment by otw** [comment]
Hi Igor,

thanks for the feedback! Hermetic testing is certainly an important topic and we carefully considered adding a sample to this repository. We decided against it because MockWebServer doesn't solve the problem for every project, since there are also architectural considerations which need to be taken into account.

Having said that we are working on a more comprehensive sample which touches on architecture + hermetic testing. Meanwhile we will publish more blog articles and pro-tips to cover hermetic app testing.
